# Generated by Django 4.2 on 2023-09-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_technicalanalysisdata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="technicalanalysisdata",
            old_name="csv_file",
            new_name="analysis_file",
        ),
    ]
